[project]
name = "sandbox"
dynamic = ["version"]
requires-python = ">= 3.10.16, < 3.11"
dependencies = [
  "black>=25.1.0",
  "isort>=6.0.1",
  "pyhidapi",
  "pylint>=3.3.6",
  "ruff>=0.11.4",
  "requests",
]

[tool.uv.workspace]
members = ["sandbox"]
